### ISSUE TITLE
markdown/any? bundle working globally if used with lintalist 1.9.14

### ISSUE THREAD

**Issue by Gewerd-Strauss** [lintalist/lintalist-bundles#5]
Hello,

I have encountered a variety of problems with lintalist since I've found it a a week ago. Two of those are posted over at the lintalist-repo itself, the third one is this here.
I am running a fresh install of lintalist 1.9.14.

This bundle, and potentially any other bundles do not work restricted to windows with the respective titlematch, but in any window. I can trigger markdown-bolding in my browser, discord, github, notepad, ahk-studio. Any application can be used to trigger markdown-specific snippets, and I don't know why.
The other problem is that lintalist doesn't restore the clipboard after pasting the snippet, but overwrites it. This happens when you let the default setting active or set the same setting specifically again. For more details, see [my issue on it](https://github.com/lintalist/lintalist/issues/193). 
I am by far not advanced enough to repair this on my own, hence I am opening an issue.

**Comment by lintalist** [comment]
Most likely you have (accidentally) "Loaded all bundles".

If you open the Lintalist search window, and then Bundles menu you will probably see a ✔ before that first option. If so, that means indeed all bundles are loaded and active. Just select "Loaded all bundles" again and it should be context sensitive again.
